"""Reading `project.json` back: the applications a generated project records, as `services.App`.

Split from `services.py` when that module reached its budget. `services` says what the list of applications
*is* and what every project-wide file derives from it; this module is the one reader that turns the written
manifest back into that list — for `add-service`, which grows a project that already exists, and `replay`,
which emits the whole project again from a newer factory — and the one place a manifest this factory does
not understand is refused.
"""
from __future__ import annotations

import json
from pathlib import Path

from .assets import VERSION
from .catalog import CATALOG
from .errors import GenerationError
from .origin import ORIGINS, origin_of  # noqa: F401 — re-exported for the manifest's readers
from .selection import Selection
from .services import App, services_of, wrapped_of

# What a manifest has to say for a command to reproduce the generation it came from. Everything else in it
# is carried through untouched, so a field a later factory adds survives an `add-service` by an older one.
REQUIRED = ("name", "profile", "frontend", "target", "deployables")

# The `project.json` shape this factory reads and writes. A project whose manifest says another number was
# generated by a factory that meant something else by these fields, and `add-service` refuses it rather
# than guessing.
MANIFEST_SCHEMA = 2

# Where a recorded fact came from, for an application the factory described rather than chose. How the
# repository itself came to have the factory's material is `origin.py`.
# `unrecorded` is the written form of "nobody has said": a fact `adopt --yes` could not read off the tree and
# nobody was asked about, kept visibly open rather than defaulted, and refreshed by the next survey that can say.
PROVENANCES = ("detected", "confirmed", "overridden", "unrecorded")


def recorded_contexts(record: dict) -> tuple[str, ...]:
    """A service's `contexts` as the manifest records them — or the one `context` a manifest written before
    a service could hold several named, read as a list of one so nothing generated then has to change."""
    contexts = record.get("contexts", [record["context"]] if "context" in record else [])
    if not isinstance(contexts, list) or not all(isinstance(name, str) for name in contexts):
        raise TypeError("'contexts' as a list of names")
    return tuple(contexts)


def wrapped_commands(record: dict) -> dict[str, str | None] | None:
    """An existing application's `commands`: one per Make target its own build answers, None for a written no."""
    commands = record.get("commands")
    if commands is None:
        return None
    if not isinstance(commands, dict) or not all(
        isinstance(target, str) and (command is None or isinstance(command, str))
        for target, command in commands.items()
    ):
        raise TypeError("'commands' as a map from Make target to command or null")
    return dict(commands)


def recorded_toolchain(record: dict) -> dict[str, str] | None:
    """What a wrapped application's build runs on, as recorded: a map of strings, or nothing."""
    toolchain = record.get("toolchain")
    if toolchain is None:
        return None
    if not isinstance(toolchain, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in toolchain.items()
    ):
        raise TypeError("'toolchain' as a map of strings")
    return dict(toolchain)


def recorded_structure(record: dict) -> str | None:
    """A wrapped application's declared `layout` — `hexagonal` puts the import gate's rules on it — or nothing."""
    structure = record.get("layout")
    if structure is not None and structure != "hexagonal":
        raise TypeError("'layout' as \"hexagonal\", or absent")
    return structure


def recorded_provenance(record: dict) -> dict[str, str]:
    """Where each of an application's facts came from, as recorded; nothing where the manifest says nothing."""
    provenance = record.get("provenance", {})
    if not isinstance(provenance, dict) or not all(
        isinstance(name, str) and origin in PROVENANCES for name, origin in provenance.items()
    ):
        raise TypeError(f"'provenance' as a map from field to one of {', '.join(PROVENANCES)}")
    return dict(provenance)


# "No `parallelSafe` in the document": not None, because the project's own mark may be JSON `null`.
ABSENT: object = object()


def recorded_parallel_safe(document: dict) -> object:
    """The project's own `parallelSafe`, as written, for a tool that regenerates its files: whatever JSON value the
    key holds (`null` included), and ABSENT where there is no key — which is what keeps a project made before the
    key serial, since no tool adds the mark (D102). The gate turns on only the JSON `true`; the value is the
    project's own, and no tool deletes or rewrites it."""
    return document.get("parallelSafe", ABSENT)


def apps_from_manifest(document: dict, allow_empty: bool = False) -> list[App]:
    """The applications a `project.json` records, refusing a manifest this factory does not understand.

    An application recorded `"generated": false` already existed when the method was installed around it:
    it is carried as written — its language, its commands, where its facts came from — and asked nothing a
    generated one is asked, which is why it needs no port and no selection.

    `allow_empty` is for the readers of an adopted repository between `adopt` and its first confirmed
    candidate (ADR 0003), where no deployable is the honest state rather than a broken manifest. It stays off
    for `add-service`, which needs one to take a language and a port from, and whose refusal this was.
    """
    if document.get("schema") != MANIFEST_SCHEMA:
        raise GenerationError(
            f"project.json has schema {document.get('schema')!r}, and this factory reads schema "
            f"{MANIFEST_SCHEMA}: it was generated by a factory that means something else by these fields"
        )
    deployables = document.get("deployables")
    if not isinstance(deployables, dict) or (not deployables and not allow_empty):
        # An adopted repository between `adopt` and its first confirmed candidate has no deployable *yet*,
        # which is a different thing from a manifest that names none — and the difference is what somebody
        # has to do next. The first real adoption to hit this was told to "add a service" by `add-frontend`,
        # having just been told by `./init` to run `slipwai add-frontend web`, with no way to know that
        # confirming a candidate was the missing step.
        outstanding = document.get("candidates")
        if isinstance(outstanding, list) and outstanding:
            named = ", ".join(
                str(row.get("name")) for row in outstanding if isinstance(row, dict) and row.get("name")
            )
            raise GenerationError(
                "project.json records no application yet — the survey found "
                f"{len(outstanding)} buildable director{'y' if len(outstanding) == 1 else 'ies'} and nobody "
                f"has said which of them is one: {named}. `/ground` asks, and `slipwai adopt --confirm "
                "<name>` records the answer; this command needs an application to sit beside."
            )
        raise GenerationError("project.json names no deployables, so there is nothing to add a service to")
    apps: list[App] = []
    for name, record in deployables.items():
        try:
            generated = record.get("generated", True)
            if generated is not True and generated is not False:
                raise TypeError("'generated' as true or false")
            service = record["kind"] == "service"
            selection = record.get("selection", {}) if service and generated else {}
            if not isinstance(selection, dict):
                raise TypeError("'selection'")
            apps.append(
                App(
                    name,
                    record["path"],
                    record["kind"],
                    record["language"],
                    record.get("framework"),
                    int(record["port"]) if generated else int(record.get("port", 0)),
                    Selection(selection),
                    record.get("api") if not service else None,
                    purpose=record.get("purpose") if service or not generated else None,
                    contexts=recorded_contexts(record) if service or not generated else (),
                    first=generated and all(app.kind != record["kind"] for app in apps if app.generated),
                    generated=generated,
                    commands=wrapped_commands(record) if not generated else None,
                    toolchain=recorded_toolchain(record) if not generated else None,
                    structure=recorded_structure(record) if not generated else None,
                    provenance=recorded_provenance(record),
                )
            )
        except (KeyError, TypeError, ValueError) as error:
            raise GenerationError(
                f"project.json's deployable '{name}' is missing {error}, which schema {MANIFEST_SCHEMA} "
                "requires"
            ) from error
    if not services_of(apps) and not wrapped_of(apps) and not (allow_empty and not apps):
        raise GenerationError("project.json records no service, only a browser app")
    return apps


class _Once(dict):
    """A JSON object that remembers which keys the text wrote more than once (RFC 8259 leaves their meaning open)."""

    repeated: list[str]


def _once(pairs: list[tuple[str, object]]) -> dict:
    held = _Once()
    held.repeated = []
    for key, value in pairs:
        if key in held:
            held.repeated.append(key)
        held[key] = value
    return held


def _paths_twice(node: object, prefix: str = "") -> list[str]:
    """Every key path the parsed text wrote more than once, at any depth."""
    found: list[str] = []
    if isinstance(node, _Once):
        found += [prefix + key for key in dict.fromkeys(node.repeated)]
    if isinstance(node, dict):
        for key, value in node.items():
            found += _paths_twice(value, f"{prefix}{key}.")
    elif isinstance(node, list):
        for index, value in enumerate(node):
            found += _paths_twice(value, f"{prefix}{index}.")
    return found


def keys_written_twice(text: str) -> list[str]:
    """The key paths `text` writes more than once, in any object at any depth; `ValueError` where it is not JSON."""
    return _paths_twice(json.loads(text, object_pairs_hook=_once))


def parse_manifest(text: str) -> object:
    """`json.loads` for a `project.json`, which refuses a key written twice rather than keeping the last copy."""
    document = json.loads(text, object_pairs_hook=_once)
    twice = _paths_twice(document)
    if twice:
        raise GenerationError(
            f'project.json has "{twice[0]}" twice' + (f" (and {len(twice) - 1} more key(s))" if len(twice) > 1 else "")
            + "; keep one copy and run this again"
        )
    return document


def load_manifest(root: Path) -> dict:
    """The parsed `project.json` of the project at `root`, with no check of what it says beyond one copy of each key."""
    return parse_manifest((root / "project.json").read_text(encoding="utf-8"))  # type: ignore[return-value]


def read_manifest(root: Path, verb: str = "add-service") -> dict:
    """The project's `project.json`, or the refusal that says why this directory is not a generated project."""
    manifest = root / "project.json"
    if not manifest.is_file():
        raise GenerationError(
            f"there is no project.json in {root}, so this is not the root of a project this factory "
            f"generated — run {verb} from that directory"
        )
    try:
        document = parse_manifest(manifest.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise GenerationError(f"project.json is not valid JSON: {error}") from error
    if not isinstance(document, dict):
        raise GenerationError("project.json is not an object")
    missing = [key for key in REQUIRED if key not in document]
    if missing:
        raise GenerationError(
            f"project.json has no {', '.join(missing)}, which this factory needs to reproduce the generation "
            "it came from — it was written by a factory that means something else by this file"
        )
    return document


def check_known(apps: list[App]) -> None:
    """Every service's backend and every answer in its selection has to be one this catalog has."""
    for service in services_of(apps):
        if service.backend not in CATALOG["backends"]:
            raise GenerationError(
                f"project.json's service '{service.name}' names the backend {service.backend!r}, which this "
                f"factory does not offer; it knows {', '.join(CATALOG['backends'])}"
            )
        for axis, chosen in service.selection.choices.items():
            if axis not in CATALOG["axes"] or chosen not in CATALOG["axes"][axis]["options"]:
                raise GenerationError(
                    f"project.json's service '{service.name}' answers {axis} with {chosen!r}, which this "
                    "factory does not know — it was written by a factory with a different catalog"
                )


def wrote_here(recorded: object) -> dict:
    """The `generator` record after a command that has just written files from *this* factory's assets.

    `updatedWith` is therefore this version, whatever the project was generated by. `generatedWith` is left
    exactly as found, and written as `null` where there is nothing to find: a repository made before the
    factory recorded this says so, rather than being credited to whichever version wrote to it later.
    """
    found = recorded if isinstance(recorded, dict) else {}
    return {"name": "slipwai", "generatedWith": found.get("generatedWith"), "updatedWith": VERSION}
