"""S08 T009 (rule 9 · AC-S08-18): what a project made before gets from `slipwai migrate`, and the fragment saying so.

The gain is `make mutation-full`, the scoped `make mutation`, `scripts/mutation-scope.py`, the changed `go-mutation.py`
and a regenerated `rules.json`. The project is generated by the factory as it stood before this slice: `git archive` of
the parent of the oldest commit that adds `scripts/mutation-scope.py`, found in this clone's history. Where the clone
does not hold that commit the example FAILS, never skips: a migrate example that passes by being skipped proves nothing.
"""
from __future__ import annotations

import importlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from support import FactoryTestCase
from test_migrate import migrate
from test_replay import git, newer_factory
from test_scoped_migrate import catch_up_paragraphs, squashed, targets_of

from slipwai.assets import ROOT

sys.dont_write_bytecode = True
FIRST = "assets/toolkit/scripts/mutation-scope.py"
FRAGMENT = ROOT / "changelog.d/scoped-mutation.md"


def factory_before() -> str | None:
    """The parent of the oldest commit in this clone's history that adds the scope script; None where there is none."""
    added = subprocess.run(["git", "log", "--diff-filter=A", "--format=%H", "--", FIRST], cwd=ROOT, text=True,
                           capture_output=True, check=False, timeout=60).stdout.split()
    if not added:
        return None
    parent = subprocess.run(["git", "rev-parse", "--verify", "-q", f"{added[-1]}^{{commit}}^"], cwd=ROOT, text=True,
                            capture_output=True, check=False, timeout=60)
    return parent.stdout.strip() or None


class AProjectMadeBeforeGainsTheScopedMutationTest(FactoryTestCase):
    def test_e6_migrate_brings_the_two_targets_the_script_and_a_gate_that_is_not_broadened(self) -> None:
        before = factory_before()
        self.assertIsNotNone(before, "the factory as it stood before this slice is not in this clone's history")
        with tempfile.TemporaryDirectory() as directory:
            old = Path(directory) / "factory-before"
            old.mkdir()
            archive = subprocess.run(["git", "archive", before or "HEAD"], cwd=ROOT, capture_output=True, check=True,
                                     timeout=120).stdout
            subprocess.run(["tar", "-x", "-C", str(old)], input=archive, check=True, timeout=120)
            subprocess.run([str(old / "slipwai"), "generate", "product", "--profile", "standard", "--backend", "go",
                            "--http", "none", "--output", directory, "--skip-checks"], check=True, capture_output=True,
                           timeout=300)
            repo = Path(directory) / "product"
            self.assertNotRegex(targets_of(repo), r"(?m)^mutation-full:")
            self.assertFalse((repo / "scripts/mutation-scope.py").exists())
            self.assertNotIn("--file", (repo / "scripts/go-mutation.py").read_text(encoding="utf-8"))
            root = git(repo, "rev-parse", "HEAD").stdout.strip()
            factory = newer_factory(Path(directory), "\n## A section a newer factory added\n")
            shutil.copytree(ROOT / "changelog.d", factory / "changelog.d")  # the fragments are the unreleased entry

            result = migrate(repo, factory)

            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            after = targets_of(repo)
            self.assertRegex(after, r"(?m)^mutation-full:")
            makefile = (repo / "Makefile").read_text(encoding="utf-8")
            self.assertIn("@python3 scripts/mutation-scope.py --make", makefile)
            self.assertTrue((repo / "scripts/mutation-scope.py").is_file())
            self.assertIn("--file", (repo / "scripts/go-mutation.py").read_text(encoding="utf-8"))
            self.assertEqual(git(repo, "status", "--porcelain").stdout, "")
            self.assertEqual(git(repo, "merge-base", "--is-ancestor", root, "HEAD", check=False).returncode, 0)
            self.not_broadened(repo)
            note = squashed((repo / ".slipwai/catch-up.md").read_text(encoding="utf-8"))
            (paragraph,) = catch_up_paragraphs(FRAGMENT.read_text(encoding="utf-8"))
            self.assertIn(squashed(paragraph).removeprefix("**Catch-up.**").strip(), note)

    def not_broadened(self, repo: Path) -> None:
        """`rules.json` is the migrated Makefile's own, and S06's judgement charges nothing: `make verify-scoped` on a
        slice branch of the project is not the full gate for any difference in the Makefile."""
        sys.path.insert(0, str(ROOT / "assets/toolkit/scripts"))
        rules = importlib.import_module("verify_scoped.rules")
        records = importlib.import_module("verify_scoped.record")
        text = (repo / "Makefile").read_text(encoding="utf-8")
        held = json.loads((repo / "scripts/verify_scoped/rules.json").read_text(encoding="utf-8"))
        self.assertEqual(held, rules.from_text(text), "rules.json is regenerated with the Makefile")
        data = records.database("make", str(repo / "Makefile"))
        names = json.loads((repo / "project.json").read_text(encoding="utf-8"))["deployables"]
        grouped = {gate: [f"{gate}-{n}" for n in names if f"{gate}-{n}" in data.needs]
                   for gate in ("lint", "typecheck", "test")}
        flat = [unit for each in grouped.values() for unit in each]
        judged = rules.judge(rules.load(str(repo / "scripts/verify_scoped/rules.json")), data, flat,
                             data.needs["verify-checks"], grouped)
        self.assertIsNone(judged.full)
        self.assertFalse(judged.checks or judged.gates)
