"""A parallel run is the serial run's verdict, a failed one ends on the gate's own line (R3, AC-S04-2 to -9, -19, -20).

Python projects generated by the factory, run against stand-in tools (`tests/parallel_gate.py`); evidence is the
stand-in `uv`'s log and make's own lines, never the clock. A **hold** is an example true before this slice's recipe
change and to stay true; each says so in its docstring and was seen to have teeth (the teeth are named there).
"""
from __future__ import annotations

import re
import sys
import unittest

from parallel_gate import ParallelGateTestCase, barrier_events, log_text, run_lines, sync_lines
from test_parallel_gate_first import OLDER

sys.dont_write_bytecode = True

CLOSING = "verify: all gates passed"
FAILED = re.compile(r"^verify: the gate did not pass; each failed check is named above on a line carrying \*\*\*$")
FORCE: dict[str, str | None] = {"VERIFY_FORCE": "1"}
# Every state that makes the gate fail here: the stand-in `uv` failing for one tool, two, or the test run.
FAILING_STATES: dict[str, dict[str, str | None]] = {
    "one check": {"STANDIN_FAIL_TOOLS": "ruff"},
    "two checks": {"STANDIN_FAIL_TOOLS": "ruff mypy", "STANDIN_BARRIER": "1"},
    "the test run": {"STANDIN_FAIL_TOOLS": "pytest"},
}


def gate_line(lines: list[str]) -> tuple[str, list[str]]:
    """The gate's own last line, and what follows it: the last line before make's own trailing `make...` lines."""
    end = len(lines)
    while end and lines[end - 1].startswith("make"):
        end -= 1
    return (lines[end - 1] if end else ""), lines[end:]


def target_lines(lines: list[str], target: str) -> list[str]:
    """make's `***` lines naming `target`, as the running make prints them: `[Makefile:7: lint] Error 1`."""
    return [line for line in lines if "***" in line and re.search(rf"\b{re.escape(target)}\]", line)]


class PassingRunTest(ParallelGateTestCase):
    SHAPE = "plain"

    def test_e1_the_commands_started_under_j_are_the_serial_runs(self) -> None:
        """HOLD (AC-S04-2; teeth: `typecheck` dropped from `verify-checks`' prerequisites under `-j` only, which loses
        its `mypy` line)."""
        self.assert_passed(self.make("verify", env=FORCE))
        serial = (sorted(run_lines(self.log)), sorted(sync_lines(self.log)))
        self.forget_log()
        self.assert_passed(self.make("-j", "verify", env=FORCE))
        self.assertEqual((sorted(run_lines(self.log)), sorted(sync_lines(self.log))), serial, log_text(self.log))
        self.assertTrue(serial[0], "the gate ran nothing")

    def test_e2_a_passing_parallel_run_exits_zero_and_ends_on_the_closing_line(self) -> None:
        """HOLD (AC-S04-3; teeth: the closing line changed in the Makefile)."""
        code, lines = self.make_merged("-j", "verify")
        self.assertEqual(code, 0, "\n".join(lines))
        self.assertEqual(lines[-1], CLOSING)
        self.assertEqual([line for line in lines if line.startswith("verify:")][-1], CLOSING)

    def test_e3_two_checks_run_at_the_same_moment(self) -> None:
        """HOLD (AC-S04-4; teeth: `.NOTPARALLEL:` in the project's Makefile makes each barrier `alone`)."""
        self.assert_passed(self.make("-j", "verify", env={"STANDIN_BARRIER": "1"}))
        self.assertEqual(barrier_events(self.log), ["met", "met"], log_text(self.log))


class FailingRunTest(ParallelGateTestCase):
    SHAPE = "plain"

    def test_e4_one_failed_check_under_j_is_non_zero_with_no_closing_line_and_no_stamp(self) -> None:
        """HOLD (AC-S04-6, -7; teeth: `record` run whatever the checks said)."""
        code, lines = self.make_merged("-j", "verify", env={"STANDIN_FAIL_TOOLS": "ruff"})
        self.assertNotEqual(code, 0, "\n".join(lines))
        self.assertNotIn(CLOSING, lines)
        self.assertEqual(self.stamps(), [], "a failed run left a stamp")

    def test_e5_two_failed_checks_are_each_named_on_a_make_line(self) -> None:
        """HOLD (AC-S04-8; teeth: one stand-in told not to fail leaves its target unnamed)."""
        code, lines = self.make_merged("-j", "verify", env=FAILING_STATES["two checks"])
        self.assertNotEqual(code, 0)
        self.assertEqual(barrier_events(self.log), ["met", "met"], "both checks must have started")
        for target in ("lint", "typecheck"):
            self.assertTrue(target_lines(lines, target), f"no *** line names {target}:\n" + "\n".join(lines))

    def test_e6_a_failed_run_ends_on_the_gates_own_line_then_makes_last(self) -> None:
        """AC-S04-9, serial and `-j`, over every state that fails: the gate's line says it did not pass and where the
        failed checks are named, and nothing after it but make's own lines; a pass prints no such line."""
        for state, extra in FAILING_STATES.items():
            for flags in ((), ("-j",)):
                if flags == () and "BARRIER" in "".join(extra):
                    continue  # serial stops at the first failure: the second check never starts to meet the first
                with self.subTest(state=state, flags=flags):
                    self.forget_log()
                    code, lines = self.make_merged(*flags, "verify", env={**FORCE, **extra})
                    self.assertNotEqual(code, 0, "\n".join(lines))
                    last, after = gate_line(lines)
                    self.assertRegex(last, FAILED, "\n".join(lines))
                    self.assertTrue(after, "make printed no last line of its own\n" + "\n".join(lines))
                    self.assertTrue(any("***" in line for line in lines), "\n".join(lines))
        for flags in ((), ("-j",)):
            with self.subTest(state="pass", flags=flags):
                self.forget_log()
                _, lines = self.make_merged(*flags, "verify", env=FORCE)
                self.assertFalse([line for line in lines if "did not pass" in line], "\n".join(lines))

    def test_e6_a_failed_sync_and_a_failed_check_python_end_on_the_same_line(self) -> None:
        """HOLD (AC-S04-9, G6): the two failures that stop the gate before any check ends on the gate's own line too.
        Teeth: take the `did not pass` echo out of the `verify` recipe."""
        older = self.bin.parent / "older"
        older.mkdir()
        (older / "sitecustomize.py").write_text(OLDER, encoding="utf-8")
        states = {"a failed sync": {"STANDIN_SYNC_FAIL": "1"}, "a failed check-python": {"PYTHONPATH": str(older)}}
        for state, extra in states.items():
            for flags in ((), ("-j",)):
                with self.subTest(state=state, flags=flags):
                    self.forget_log()
                    code, lines = self.make_merged(*flags, "verify", env={**FORCE, **extra})
                    self.assertNotEqual(code, 0, "\n".join(lines))
                    last, after = gate_line(lines)
                    self.assertRegex(last, FAILED, "\n".join(lines))
                    self.assertTrue(after and any("***" in line for line in lines), "\n".join(lines))

    def test_e6_a_script_of_the_project_failing_ends_on_the_same_line(self) -> None:
        """AC-S04-9 for a `python3` check that fails, serial and `-j`."""
        script = self.repo / "scripts" / "check-imports.py"
        script.write_text("import sys\nsys.exit(1)\n", encoding="utf-8")
        for flags in ((), ("-j",)):
            with self.subTest(flags=flags):
                code, lines = self.make_merged(*flags, "verify")
                self.assertNotEqual(code, 0)
                self.assertRegex(gate_line(lines)[0], FAILED, "\n".join(lines))
                self.assertTrue(target_lines(lines, "check-imports"), "\n".join(lines))


class ReuseAcrossTheTwoTest(ParallelGateTestCase):
    SHAPE = "plain"

    def test_e7_a_pass_under_j_is_reused_by_make_verify(self) -> None:
        """HOLD (AC-S04-19; teeth: `record` skipped under `-j`)."""
        self.assert_passed(self.make("-j", "verify"))
        self.assertTrue(self.stamps(), "no stamp after a pass")
        self.forget_log()
        done = self.make("verify")
        self.assert_passed(done)
        self.assertEqual(run_lines(self.log), [], "the reuse ran a check\n" + log_text(self.log))
        self.assertNotIn(CLOSING, done.stdout)

    def test_e8_a_pass_under_make_verify_is_reused_by_j(self) -> None:
        """HOLD (AC-S04-20; teeth: `record` skipped under serial)."""
        self.assert_passed(self.make("verify"))
        self.forget_log()
        done = self.make("-j", "verify")
        self.assert_passed(done)
        self.assertEqual(run_lines(self.log), [], "the reuse ran a check\n" + log_text(self.log))
        self.assertNotIn(CLOSING, done.stdout)


class EventProfileTest(ParallelGateTestCase):
    SHAPE = "db"

    def test_the_closing_line_is_last_on_a_pass_and_the_failed_line_on_a_fail(self) -> None:
        """AC-S04-3, -9 on the event profile, whose prerequisites differ from the standard's."""
        code, lines = self.make_merged("-j", "verify")
        self.assertEqual((code, lines[-1]), (0, CLOSING), "\n".join(lines))
        self.forget_log()
        code, lines = self.make_merged("-j", "verify", env={"STANDIN_FAIL_TOOLS": "ruff", "VERIFY_FORCE": "1"})
        self.assertNotEqual(code, 0)
        self.assertNotIn(CLOSING, lines)
        self.assertRegex(gate_line(lines)[0], FAILED, "\n".join(lines))

if __name__ == "__main__":
    unittest.main()
