"""S41 T012 (rule 10 · AC-S41-12): a project made before this slice is brought forward; the fragment says how.

The factory as it stood before the slice is the parent of the oldest commit in this clone that adds
`src/slipwai/project/stryker.py`, found in the history every clone that runs the suite holds (the technique of
`test_scoped_migrate`); where the clone is too shallow to hold it the examples FAIL, since a migrate example that
passes by being skipped proves nothing. A project is generated by that factory, then migrated by this checkout's copy
raised to a newer version, as `test_scoped_migrate` does.
"""
from __future__ import annotations

import importlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from stamp_fixture import CI_MARKERS, GIT_STATE, MAKE_STATE
from stamp_fixture import git as repo_git
from support import FactoryTestCase, commit_all
from test_migrate import migrate
from test_replay import newer_factory

from slipwai.assets import ROOT

sys.dont_write_bytecode = True
sys.path.insert(0, str(ROOT / "assets" / "toolkit" / "scripts"))
FRAGMENT = ROOT / "changelog.d/stryker-mutation.md"
FIRST = ("src", "slipwai", "project", "stryker.py")
WRAPPER = ("scripts", "stryker-mutation.py")
CONFIG = "stryker.config.json"
CATCH_UP_WORDS = ("`package-lock.json`", "`npm install`", "wired by hand", "`make mutation-full`", "recorded stub",
                  "No `project.json` key changes")


def factory_before() -> str | None:
    """The factory as it stood before the slice: the parent of the oldest commit that adds the slice's module."""
    added = subprocess.run(["git", "log", "--diff-filter=A", "--format=%H", "--", "/".join(FIRST)], cwd=ROOT, text=True,
                           capture_output=True, check=False, timeout=60).stdout.split()
    if not added:
        return None
    parent = subprocess.run(["git", "rev-parse", "--verify", "-q", f"{added[-1]}^{{commit}}^"], cwd=ROOT, text=True,
                            capture_output=True, check=False, timeout=60)
    return parent.stdout.strip() or None


BEFORE = factory_before()


def squashed(text: str) -> str:
    return " ".join(text.split())


class FragmentTest(unittest.TestCase):
    def test_e1_the_fragment_is_minor_and_its_catch_up_stands_alone_and_says_what_it_asks(self) -> None:
        text = FRAGMENT.read_text(encoding="utf-8")
        self.assertEqual(text.splitlines()[0], "MINOR")
        paragraphs = [block for block in text.split("\n\n") if block.startswith("**Catch-up.**")]
        self.assertEqual(len(paragraphs), 1)
        note = squashed(paragraphs[0])
        for words in CATCH_UP_WORDS:
            self.assertIn(words, note)
        for words in ("stryker.config.json", "scripts/stryker-mutation.py", "Python", "java-quarkus"):
            self.assertIn(words, note)


class MigrateTest(FactoryTestCase):
    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        if BEFORE is None:
            raise AssertionError("the factory as it stood before the Stryker slice is not in this clone's history: "
                                 "the migrate examples would pass by being skipped")

    def old_project(self, directory: str, backend: str = "typescript", added: tuple[str, ...] = ()) -> Path:
        """A project the factory before the slice generated: `git archive` of that commit and its own `generate`."""
        old = Path(directory) / "factory-before"
        old.mkdir()
        archive = subprocess.run(["git", "archive", BEFORE or "HEAD"], cwd=ROOT, capture_output=True, check=True,
                                 timeout=120).stdout
        subprocess.run(["tar", "-x", "-C", str(old)], input=archive, check=True, timeout=120)
        subprocess.run([str(old / "slipwai"), "generate", "product", "--profile", "standard", "--backend", backend,
                        "--frontend", "none", "--http", "none", "--output", directory, "--skip-checks"], check=True,
                       capture_output=True, timeout=300)
        repo = Path(directory) / "product"
        for name in added:
            if repo_git(repo, "status", "--porcelain").strip():
                commit_all(repo, "before " + name)
            subprocess.run([str(old / "slipwai"), "add-service", name, "--language", "typescript"], cwd=repo,
                           check=True, capture_output=True, timeout=300)
        return repo

    def migrated(self, directory: str, repo: Path) -> subprocess.CompletedProcess[str]:
        if repo_git(repo, "status", "--porcelain").strip():
            commit_all(repo, "as the old factory left it")
        factory = newer_factory(Path(directory), "\n## A section a newer factory added\n")
        shutil.copytree(ROOT / "changelog.d", factory / "changelog.d")  # the fragments are the unreleased entry
        return migrate(repo, factory)

    def test_e2_a_typescript_project_gains_the_dependencies_the_config_the_wrapper_and_the_ignore_lines(self) -> None:
        import importlib
        rules = importlib.import_module("verify_scoped.rules")
        with tempfile.TemporaryDirectory() as directory:
            repo = self.old_project(directory)
            self.assertFalse((repo / "/".join(WRAPPER)).exists(), "the factory as it was had no such script")
            result = self.migrated(directory, repo)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            manifest = json.loads((repo / "apps/service/package.json").read_text(encoding="utf-8"))
            for package in ("core", "vitest-runner"):
                self.assertEqual(manifest["devDependencies"][f"@stryker-mutator/{package}"], "10.0.0")
            self.assertTrue((repo / "apps/service" / CONFIG).is_file())
            self.assertTrue(Path(repo / "/".join(WRAPPER)).stat().st_mode & 0o100)
            ignored = (repo / ".gitignore").read_text(encoding="utf-8").splitlines()
            self.assertIn(".stryker-tmp/", ignored)
            self.assertIn("apps/*/reports/mutation/", ignored)
            makefile = repo / "Makefile"
            self.assertIn("\tpython3 scripts/stryker-mutation.py apps/service\n", makefile.read_text(encoding="utf-8"))
            self.assertIsNone(rules.text_problem(str(makefile), str(repo / "scripts/verify_scoped/rules.json"), {}),
                              "the scoped gate would be broadened: rules.json is not the Makefile's digest")
            self.assertEqual(repo_git(repo, "status", "--porcelain").strip(), "")

    def test_e3_a_hand_edited_manifest_keeps_its_edit_and_a_stryker_file_of_the_project_s_own_stays(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            repo = self.old_project(directory)
            manifest = repo / "apps/service/package.json"
            document = json.loads(manifest.read_text(encoding="utf-8"))
            document["devDependencies"]["zod"] = "3.25.0"
            manifest.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
            commit_all(repo, "the product's own dependency")
            result = self.migrated(directory, repo)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            merged = json.loads(manifest.read_text(encoding="utf-8"))["devDependencies"]
            self.assertEqual((merged["zod"], merged["@stryker-mutator/core"]), ("3.25.0", "10.0.0"))
        with tempfile.TemporaryDirectory() as directory:
            repo = self.old_project(directory)
            own = repo / "apps/service" / CONFIG
            own.write_text('{"testRunner": "vitest", "mutate": ["src/**/*.ts"], "mine": true}\n', encoding="utf-8")
            commit_all(repo, "the product wired Stryker by hand")
            result = self.migrated(directory, repo)
            self.assertNotEqual(result.returncode, 0, "a file the project wrote was overwritten without a word")
            self.assertIn(f"apps/service/{CONFIG}", result.stdout + result.stderr)
            self.assertIn('"mine": true', own.read_text(encoding="utf-8"))

    def test_e4_a_go_project_gains_no_stryker_file_and_two_typescript_services_get_one_config_each_and_one_wrapper(
            self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            repo = self.old_project(directory, "go")
            result = self.migrated(directory, repo)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertEqual(sorted(p.name for p in repo.rglob("*stryker*") if ".git" not in p.parts), [])
        with tempfile.TemporaryDirectory() as directory:
            repo = self.old_project(directory, "typescript", ("second",))
            result = self.migrated(directory, repo)
            # A project that added a service has changed the lines the factory changed: migrate lists them for the
            # project to settle, as for every such project, and the Stryker files it adds are merged and staged.
            self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
            for conflict in ("Makefile", "apps/second/package.json", "package-lock.json",
                             "scripts/verify_scoped/rules.json"):
                self.assertIn(f"  {conflict}\n", result.stdout + result.stderr)
            self.assertEqual(sorted(str(p.relative_to(repo)) for p in repo.rglob("*stryker*") if ".git" not in p.parts),
                             ["apps/second/stryker.config.json", "apps/service/stryker.config.json",
                              "scripts/stryker-mutation.py"])




    def test_e5_following_the_catch_up_on_an_add_service_project_ends_consistent(self) -> None:
        """T030: the paragraph names each conflict, the devDependencies and their version; its steps end in a
        `Makefile` the factory wrote, a `rules.json` that matches it and a lock `npm ci` accepts; the edit it warns of
        does what it says. No command rewrites `rules.json` (ADR 0005), so the paragraph names none."""
        rules = importlib.import_module("verify_scoped.rules")
        text = FRAGMENT.read_text(encoding="utf-8")
        catch_up = squashed(next(block for block in text.split("\n\n") if block.startswith("**Catch-up.**")))
        with tempfile.TemporaryDirectory() as directory:
            repo = self.old_project(directory, "typescript", ("second",))
            result = self.migrated(directory, repo)
            reported = set(re.findall(r"^  (\S+)$", result.stdout + result.stderr, re.M))
            self.assertEqual(reported, {"Makefile", "apps/second/package.json", "package-lock.json",
                                        "scripts/verify_scoped/rules.json"})
            for name in ("Makefile", "package-lock.json", "scripts/verify_scoped/rules.json",
                         "apps/<service>/package.json"):
                self.assertIn(f"`{name}`", catch_up)
            for package in ("@stryker-mutator/core", "@stryker-mutator/vitest-runner"):
                self.assertIn(f"`{package}`", catch_up)
            self.assertIn("`10.0.0`", catch_up)
            for name in reported:  # "take the factory's side of all four", as the paragraph says
                repo_git(repo, "checkout", "--theirs", "--", name)
                repo_git(repo, "add", name)
            makefile, record = str(repo / "Makefile"), str(repo / "scripts/verify_scoped/rules.json")
            self.assertIsNone(rules.text_problem(makefile, record, {}))
            manifest = json.loads((repo / "apps/second/package.json").read_text(encoding="utf-8"))
            self.assertEqual({k: v for k, v in manifest["devDependencies"].items() if k.startswith("@stryker")},
                             {"@stryker-mutator/core": "10.0.0", "@stryker-mutator/vitest-runner": "10.0.0"})
            if shutil.which("npm") is not None:
                env = {k: v for k, v in os.environ.items() if k not in CI_MARKERS + MAKE_STATE + GIT_STATE}
                for command in (["npm", "install", "--package-lock-only", "--offline", "--ignore-scripts"],
                                ["npm", "ci", "--dry-run", "--offline", "--ignore-scripts"]):
                    done = subprocess.run(command, cwd=repo, env=env, text=True, capture_output=True, check=False,
                                          timeout=180)
                    self.assertEqual(done.returncode, 0, " ".join(command) + "\n" + done.stdout + done.stderr)
            # The edit the paragraph warns of: a line of one's own leaves `rules.json` describing another file.
            (repo / "Makefile").write_text((repo / "Makefile").read_text(encoding="utf-8") + "\nmine:\n\t@true\n",
                                           encoding="utf-8")
            self.assertIn("scoped gate", rules.text_problem(makefile, record, {}) or "")
        self.assertIn("run the full gate", catch_up)
