"""`.gitignore`: what this project's toolchain writes, and the data it must never commit."""
from __future__ import annotations

import json

from ..assets import NOTES, TOOLKIT_ROOT
from ..catalog import CATALOG
from ..extensions import known_extensions
from ..services import App, backends_of, families_of, needs_environment, services_of, web_apps
from ..targets import managed
from .cruise_record import (
    CHECKPOINT,
    INBOX,
    LAST_RESPONSE,
    RUNNER_LOG,
    RUNNER_PID,
    RUNNER_STREAM,
    STOP_FILE,
    TOLD,
    WATCH_CURSOR,
)
from .openapi import API_CLIENT
from .shared_packages import PACKAGES, node_workspace

# What each store writes beside the code, keyed by feature, for a store that keeps its data in the working
# tree. A SQLite event store writes its log next to the code, and WAL mode writes two more files beside it.
# An event log is the one thing in a project that must never be committed: it is data, it is often
# personal, and a merge of two histories is not a history. A store with a container writes nothing here.
STORE_ARTIFACTS = {
    "sqlite": "*.sqlite3\n*.sqlite3-wal\n*.sqlite3-shm\n",
}
# The five slice-scoped artifacts the installed Spec Kit commands write at the feature root.
CANONICAL_SLOTS = ("plan.md", "research.md", "data-model.md", "quickstart.md", "tasks.md")


# Every directory an agent harness's projection lands in (`scripts/agents/registry.json`), read once. The projections
# are derived files — the canonical `skills/`, `commands/` and `agents/` again, with a stamp — written by `./init`,
# `make agents` and `slipwai migrate`, and `check-agents` reads an absent one as a clone nobody has run `./init` in
# yet. Committing them put the whole skill catalogue, thirty thousand lines, into every repository twice; nothing read the
# copy that the canonical file did not say.
REGISTRY = TOOLKIT_ROOT / "scripts/agents/registry.json"


def harness_directories(entry: dict) -> list[str]:
    """Every directory this harness's projections land in: its skills, its commands and its agent types."""
    named = [entry.get(key) for key in ("skillsDir", "commandsDir")]
    if isinstance(entry.get("agentFile"), dict):
        named.append(entry["agentFile"].get("dir"))
    return [value for value in named if isinstance(value, str) and not value.startswith(("~", "/"))]


def projection_artifacts() -> str:
    """One ignored line per harness directory inside the repository, once each, in registry order."""
    harnesses = json.loads(REGISTRY.read_text(encoding="utf-8"))["harnesses"]
    directories = [directory for entry in harnesses for directory in harness_directories(entry)]
    return "".join(f"{directory.rstrip('/')}/\n" for directory in dict.fromkeys(directories))


def build_artifacts(event: bool, apps: list[App], target: str = "none") -> str:
    """Every backend's artifacts once each, then the frontend's, the event profile's, the selection's and the
    production target's."""
    per_backend = {
        # Stryker's sandbox and report first: a line added above the block merges cleanly under `migrate` with the
        # lines `add-service` appends below it, where the same lines added at its end conflicted with them.
        "typescript": ".stryker-tmp/\napps/*/reports/mutation/\nnode_modules/\ncoverage/\n.build/\n",
        # `.venv/` is what `uv sync` builds beside each service's manifest, from the committed `uv.lock`
        # that *is* committed. `apps/*/requirements.txt` is the runtime half of that lock, exported by
        # `make build` for the buildpack and thrown away after: derived from the lock, never edited, and a
        # committed copy would be the second dependency list this backend exists without.
        "python": (
            "__pycache__/\n*.pyc\n.venv/\n.pytest_cache/\n.ruff_cache/\n/apps/*/requirements.txt\n"
        ),
        # `coverage.out` is what `make test` writes beside the service; `gremlins.json` is what
        # `make mutation` now copies out of its staging tree, for the same reason and with the same
        # lifetime — a report of one run on one machine, read once and regenerated by the next run.
        "go": "coverage.out\ngremlins.json\n",
        # `target/` is every artifact Maven writes — classes, the Quarkus build output, the analysers'
        # reports. `.flattened-pom.xml` is what the Quarkus build leaves behind when it resolves the
        # platform BOM, and it is derived from the pom rather than edited beside it.
        "java-quarkus": "target/\n.flattened-pom.xml\n",
        # `target/` for the same reason, and nothing else: Spring Boot's plugin writes the repackaged jar
        # and the `build-info` inside it rather than beside the pom, so there is no second file to ignore.
        "java-spring": "target/\n",
    }
    language_artifacts = "".join(dict.fromkeys(per_backend[backend] for backend in backends_of(apps)))
    frontend_artifacts = "".join(f"{web.path}/dist/\n" for web in web_apps(apps))
    # Of the family, not the backend: a TypeScript service behind any framework already ignores
    # node_modules for its own sake, and a second copy of the line is not the answer for either.
    if web_apps(apps) and "typescript" not in families_of(apps):
        frontend_artifacts = "node_modules/\n" + frontend_artifacts
    # Rendered Mermaid artifacts are CI-owned: the pages workflow regenerates them on every model change,
    # and nothing browser-free can prove a committed copy is current, so none is committed. The draw.io
    # canvas beside them, `docs/event-model/model.drawio`, is the one rendering that *is* committed — it
    # needs no browser, and `check-drawio` proves it current inside `verify` — so it is not listed here.
    event_artifacts = (
        "scripts/event-model/node_modules/\n"
        "scripts/event-model/.mermaid-cli/\n"
        "docs/event-model/model.mmd\n"
        "docs/event-model/model.svg\n"
        "docs/event-model/model.png\n"
        "docs/event-model/model.html\n"
        "docs/event-model/slices/\n"
        "docs/event-model/segments/\n"
        if event
        else ""
    )
    # What `make build-packages` writes, on the same reasoning as `.env` below: an ignored path that nothing
    # has created yet costs nothing, and the alternative is the first `packages/<name>` somebody adds
    # arriving with its `dist/` committed — a build output in the history, which is how a stale one comes to
    # look like a current one. `dist/` because that is the convention the browser app beside it already uses.
    shared_package_artifacts = f"{PACKAGES}/*/dist/\n" if node_workspace(apps) else ""
    # And the typed client's generated types, on the same reasoning: `make build-packages` writes them from
    # the service's published document, so a committed copy is one that can disagree with the contract
    # while looking authoritative — and a generated file in the tree is a file somebody edits.
    if node_workspace(apps):
        shared_package_artifacts += f"{API_CLIENT}/src/schema.ts\n"
    # `.env` holds the local values copied out of `.env.example`, including a database URL with a password
    # in it. Ignored whether or not the services survive a later prune: an ignored path that no longer
    # exists costs nothing, and an un-ignored one that does is a committed credential.
    environment_artifacts = ".env\n" if needs_environment(apps) else ""
    store_artifacts = "".join(
        dict.fromkeys(
            STORE_ARTIFACTS.get(service.selection.feature_of("event-store") or "", "")
            for service in services_of(apps)
        )
    )
    # What `make push` and `make deploy` write locally, and what `tofu init` keeps beside each stack. The
    # bootstrap stack's state is deliberately *not* here: it is committed, encrypted, on purpose.
    production_artifacts = (
        ".build/\ninfra/**/.terraform/\ninfra/**/*.tfplan\ninfra/**/terraform.tfstate.backup\n"
        if managed(CATALOG, target)
        else ""
    )
    # Every extension's local state, whether or not `./init --extension <key>` was ever run: an ignored
    # path that does not exist yet costs nothing, same reasoning as `.env` above, and it means adopting an
    # extension later never needs a second edit to `.gitignore`.
    extension_artifacts = "".join(
        extension.get("ignore", "") for extension in known_extensions(CATALOG).values()
    )
    return (
        language_artifacts
        + frontend_artifacts
        + shared_package_artifacts
        + event_artifacts
        + environment_artifacts
        + store_artifacts
        + production_artifacts
        + extension_artifacts
        # What a factory command leaves for this project to act on and then throw away. Only the catch-up
        # page is ignored: `.slipwai/extensions.json` beside it is the committed election record migration
        # needs in order to re-project extensions without asking the interactive menu again.
        + f"{NOTES}\n"
        + ".specify-tools/\n.delivery-tools/\n"
        # The canonical slot the installed Spec Kit plan and tasks commands resolve to, one per feature. Since
        # 1.15.0 it is a link into `specs/<feature>/slices/<id>/`, where a slice's record lives from the day it
        # is planned, so two slices of one feature never overwrite each other's plan. The link is local
        # scaffolding — committed, it would point somewhere different on every slice branch and conflict at
        # every merge — and `check-slice-scope` refuses a regular file left where the link was.
        + "".join(f"specs/*/{slot}\n" for slot in CANONICAL_SLOTS)
        # `/cruise`'s checkpoint: the state of the iteration in flight, rewritten at every stage boundary so a
        # compacted context can resume, and deleted when the iteration ends — run state, never a record.
        + f"{CHECKPOINT}\n"
        # The runner's own state beside it: a person's stop signal, the pid of the runner, where a detached runner
        # writes what a foreground one prints, the raw stream that feed was rendered from, how far the watch seat
        # has read it, the last message a harness's after-response hook kept, and what a person queued for the run
        # and an iteration was given — each of which is in the iteration log once delivered.
        + f"{STOP_FILE}\n{RUNNER_PID}\n{RUNNER_LOG}\n{RUNNER_STREAM}\n{WATCH_CURSOR}\n{LAST_RESPONSE}\n"
        + f"{INBOX}\n{TOLD}\n"
        # The agent projections: derived from `skills/`, `commands/` and `agents/`, rewritten by `./init`, `make agents` and
        # `slipwai migrate`, and never the place to edit — so never committed, whichever harness the project uses.
        + projection_artifacts()
    )
